[package]
name = "amicola"
version = "0.1.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2.8"
nalgebra = "0.18.0"
geo = "0.12.2"
failure = "0.1.5"
failure_derive = "0.1.5"
image = "0.22.1"
rayon = "1.1.0"
log = "0.4.8"
