[package]
name = "amicola"
version = "0.1.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]
edition = "2018"

[dependencies]
amicola_types = {path = "amicola_types"}
amicola_algo = {path = "amicola_algo"}

[workspace]
members = ["amicola_types", "amicola_algo"]