[package]
name = "valora"
version = "0.1.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2.8"
nalgebra = "0.18.0"
geo = "0.12.2"
failure = "0.1.5"
failure_derive = "0.1.5"
image = "0.22.1"
rayon = "1.1.0"
derive_more = { git = "https://github.com/JelteF/derive_more.git" }
rand = "0.7.0"
structopt = "0.3.0"
palette = "0.4.1"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_warn"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
