[package]
name = "valora_derive"
version = "0.1.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]
edition = "2018"
description = "Derives for valora."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.11"
proc-macro2 = "1.0.6"
quote = "1.0.2"
heck = "0.3.1"
